/*
 *	Name: Mathematics
 *	Author: Pawel Mrochen
 */

#pragma once

#include "Constants.hpp"
#include "Scalar.hpp"
#include "Axis.hpp"
#include "EulerOrder.hpp"
#include "Vector2.hpp"
#include "Vector3.hpp"
#include "Vector4.hpp"
#include "Matrix2.hpp"
#include "Matrix3.hpp"
#include "AffineTransform.hpp"
#include "Matrix4.hpp"
#include "Quaternion.hpp"
#include "YawPitchRoll.hpp"
#include "Euler.hpp"
#include "Interval.hpp"
#include "Line2.hpp"
#include "Line3.hpp"
#include "Ray2.hpp"
#include "Ray3.hpp"
#include "LineSegment2.hpp"
#include "LineSegment3.hpp"
#include "BezierCurve2.hpp"
#include "BezierCurve3.hpp"
#include "HalfSpace.hpp"
#include "Plane.hpp"
#include "Triangle3.hpp"
#include "Quadrilateral3.hpp"
#include "Tetrahedron.hpp"
#include "AxisAlignedRectangle.hpp"
#include "AxisAlignedBox.hpp"
#include "OrientedBox.hpp"
#include "Circle2.hpp"
#include "Sphere.hpp"
#include "Ellipsoid.hpp"
#include "Torus.hpp"
#include "Cylinder.hpp"
#include "Capsule.hpp"
#include "Cone.hpp"
#include "SymmetricFrustum.hpp"
#include "ConvexPolyhedron.hpp"
//#include "TriangleMesh.hpp"
//#include "TetrahedralMesh.hpp"
