/*
 *	Name: Mathematics
 *	Author: Pawel Mrochen
 */

#pragma once

#include "Constants.hpp"
#include "Scalar.hpp"
#include "Geometry/Axis.hpp"
#include "Transform/EulerOrder.hpp"
#include "Algebra/Vector2.hpp"
#include "Algebra/Vector3.hpp"
#include "Algebra/Vector4.hpp"
#include "Algebra/Matrix2.hpp"
#include "Algebra/Matrix3.hpp"
#include "Transform/AffineTransform.hpp"
#include "Algebra/Matrix4.hpp"
#include "Algebra/Quaternion.hpp"
#include "Transform/YawPitchRoll.hpp"
#include "Transform/Euler.hpp"
#include "Interval.hpp"
#include "Geometry/Line2.hpp"
#include "Geometry/Line3.hpp"
#include "Geometry/Ray2.hpp"
#include "Geometry/Ray3.hpp"
#include "Geometry/LineSegment2.hpp"
#include "Geometry/LineSegment3.hpp"
#include "Geometry/BezierCurve2.hpp"
#include "Geometry/BezierCurve3.hpp"
#include "Geometry/HalfSpace.hpp"
#include "Geometry/Plane.hpp"
#include "Geometry/Triangle3.hpp"
#include "Geometry/Quadrilateral3.hpp"
#include "Geometry/Tetrahedron.hpp"
#include "Geometry/AxisAlignedRectangle.hpp"
#include "Geometry/AxisAlignedBox.hpp"
#include "Geometry/OrientedBox.hpp"
#include "Geometry/Circle2.hpp"
#include "Geometry/Sphere.hpp"
#include "Geometry/Ellipsoid.hpp"
#include "Geometry/Torus.hpp"
#include "Geometry/Cylinder.hpp"
#include "Geometry/Capsule.hpp"
#include "Geometry/Cone.hpp"
#include "Geometry/SymmetricFrustum.hpp"
#include "Geometry/ConvexPolyhedron.hpp"
#include "Geometry/TriangleMesh.hpp"
#include "Geometry/TetrahedralMesh.hpp"
#include "Random.hpp"
